name: Auto Label on Issue Events

on:
  issues:
    types: [opened, closed, reopened]
    
permissions:
  issues: write
  
jobs:
  manage-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Remove "done" label when issue is opened
        if: github.event.action == 'opened'
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: "done"

      - name: Add "to-be-done" label when issue is opened
        if: github.event.action == 'opened'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: "to-be-done"

      - name: Add "done" label when issue is closed
        if: github.event.action == 'closed'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: "done"

      - name: Remove "done" label when issue is reopened
        if: github.event.action == 'reopened'
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: "done"

      - name: Add "to-be-done" label when issue is reopened
        if: github.event.action == 'reopened'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: "to-be-done"
